config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :products do
    resources :bookings, only: [:new, :create]
  end
  
  resources :bookings, only: [:edit, :update, :destroy]
  get '/profile', to: "pages#profile"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :product
  enum status: [:accepted, :pending, :rejected]
  validates :rating, inclusion: { in: (0..5) }

  def pending?
    status == 'pending'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  CATEGORY = ["Tent", "Camp Kitchen", "Sleeping Bags", "Hammocks"]
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :category, presence: true
  validates :price, numericality: { greater_than: 1 }
  validates :category, inclusion: { in: CATEGORY }

  include PgSearch::Model
  pg_search_scope :search_by_name,
    against: [ :name ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  def self.pick_random
    self.order(Arel.sql('RANDOM()')).first(3)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  has_many :bookings, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :bookings_as_owner, through: :products, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[edit update destroy]

  def new
    @booking = Booking.new
    @product = Product.find(params[:product_id])
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @user = current_user
    @product = Product.find(params[:product_id])
    @booking.product = @product
    @booking.user = @user
    authorize @booking
    if @booking.save
      redirect_to profile_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.update(booking_params)
     redirect_to profile_path
    else
     render "new"
    end
  end

  def destroy
    authorize @booking
    @booking.destroy
    redirect_to products_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :status, :comment, :rating, :user, :product)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def profile
    @user = User.find(params[:id])
    @booking = Booking.find(params[:user])
    # @listing =
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    if params[:query].present?
      # @products = Product.where("name ILIKE ?", "%#{params[:query]}%")
      @products = Product.search_by_name(params[:query])
    else
      @products = Product.all
    end
  end

   def profile
    @user = current_user
    start_date = params.fetch(:start_date, Date.today).to_date
    @bookings = Booking.where(user: @user, start_time: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
    @rental_bookings =  current_user.bookings_as_owner
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  skip_after_action :verify_policy_scoped, only: :index
  before_action :set_product, only: %i[show destroy]

  def index
    if params[:query].present?
      @query = params[:query]
      # @products = policy_scope(Product.where("name LIKE ?", "%#{params[:query]}%"))
      @products = Product.search_by_name(@query)

    else
      @products = policy_scope(Product)
    end

     @markers = @products.map do |product|
      {
        lat: product.user.latitude,
        lng: product.user.longitude,
        info_window: render_to_string(partial: "info_window", locals: { product: product })
      }
     end
  end

  def show
    @random_product = Product.pick_random
    authorize @product
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    @user = current_user
    @product.user = @user
    authorize @product
    if @product.save
      redirect_to product_path(@product)
    else
      render 'new'
    end
  end

  def destroy
    authorize @product
    @product.destroy
    redirect_to products_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :picture, :category, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [product, booking] do |f| %>
  <div class="d-flex justify-content-between py-3">
     <%= f.input :start_time, as: :string, required: false, input_html: {class: "datepicker"} %>
     <%= f.input :end_time, as: :string, required: false, input_html: {class: "datepicker"} %>
   </div>
   <div>
     <p id='priceElement' data-price="<%= product.price %>">¥ <%= product.price %> /day </p>
   </div>
   <button class="add-to-cart" type="submit">Request</button>
   <%#= f.button class: 'add-to-cart' %>
<% end %>

app/views/bookings/edit.html.erb
<%#= render "form", booking: @booking %>

<%= simple_form_for(booking) do |f| %>
  <%= f.input :rating %>
  <%= f.input :comment %>
  <%= f.input :status %>
  <%= f.input :date_start %>
  <%= f.input :date_end %>
  <%= f.submit %>
<% end %>

app/views/bookings/new.html.erb
<div class="p-5 d-flex justify-content-center align-items-center container">
  <div class="row">
    <div class="d-flex justify-content-between align-items-center">
      <div class="my-5">
      <h1>New reservation</h1>
      <%= render 'form', product: @product, booking: @booking %>
      </div>
      <div>
        <%= cl_image_tag @product.photos[0].key, width: 500, class: "mx-5" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CampQ</title>
    <link rel="ico" type="image/png" href="public/favicon.ico">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
    <body>

    <%= render "shared/navbar" %>
  
    <%= yield %>
  
    <%= render "shared/footer" %>

  </body>
</html>

app/views/pages/_gear_card.html.erb
<div class="bookings m-3">
  <% bookings.each do |booking| %>
    <div class="booking-card border-bottom pb-5">
      <div class='booking-left'>
        <!-- if you're using cloudinary and activestorage -->
        <%= cl_image_tag booking.product.photos[0].key, class: 'product-picture' %>
        <div class="booking-info mx-5">
          <div class="booking-info-details">
            <div class="info-section border-bottom">
              <p class="booking-info-small">A reservation for </p>
              <%= booking.product.name %>
            </div>
            <div class="info-section">
              <p class="booking-info-small">Has been requested by</p>
              <%= booking.user.first_name %> <%= booking.user.last_name %>
            </div>
          </div>
          <div class="booking-info-time info-section">
            <p class="booking-info-small py-0 mb-2"></p>
            <%= booking.start_time.strftime('%a, %B %d, %Y') %> - <%= booking.end_time.strftime('%a, %B %d, %Y') %>
          </div>
          <div class="info-section mt-4 d-flex">
            <div>
              <p class="pe-3">Total price: </p>
            </div>
            <div class="mx-1">
              <% if (booking.start_time.to_i - booking.end_time.to_i) > -86400 %>
                <%= booking.product.price %> ¥
              <% else %>
                <%= ((booking.start_time.to_i - booking.end_time.to_i) / -86400) * booking.product.price %> ¥
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="booking-actions">
        <% if booking.pending? && current_user != booking.user %>
          <%= simple_form_for booking do |f| %>
            <%= f.input :status, as: :hidden, input_html: { value: :accepted} %>
            <%= f.submit 'Accept', class: 'btn btn-primary m-3' %>
          <% end %>
          <%= simple_form_for booking do |f| %>
            <%= f.input :status, as: :hidden, input_html: { value: :rejected} %>
            <%= f.submit 'Reject', class: 'btn btn-outline-info m-3' %>
          <% end %>
        <% else %>
          <p class='booking-tag'><%= booking.status %> </p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<!--   <h1>My Gear</h1>
      <%#= render 'gear_card', bookings: @bookings %> -->

app/views/pages/_listing_card.html.erb
<section class="product-cards">
  <% products.each do |product| %>
    <div class="card-trip">
      <% link_to(product_path(product)) %>
      <%= cl_image_tag product.photos[1].key, width: 100 %>
      <div class="card-trip-infos">
       <div style="display: ;">
         <figcaption><%= link_to product.name, product_path(product) %></figcaption>
         <figcaption><strong>$<%= product.price %></strong></figcaption>
       </div>
      </div>
    </div>
  <% end %>
</section>

app/views/pages/_popular-card.html.erb
 <div class="card-popular" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path product.photos[1].key %>)">
  <p><%= product.name %></p>
  </div>

app/views/pages/_profile_calendar.html.erb
<div>
  <%= month_calendar(events: bookings+rental_bookings, attribute: :start_time, end_attribute: :end_time) do |date, bookings| %>
    <%= date %>
    <% bookings.each do |booking| %>
      <div class="booking-profile-calendar">
        <p><%= booking.product.name.split(' ')[0] %></p>
        <p><%= booking.status %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/pages/_profile_tab.html.erb
<div class="dashboard_card my-3">
  <div>
    <%= image_tag current_user.picture, class: "avatar-profile" %>
  </div>
  <div class="dashboard-info mt-4 p-3 border-top">
    <div class="pb-2">
      <%= user.first_name %> <%= user.last_name %>
    </div>
    <div class="pb-2">
      <%= user.email %>
    </div>
    <div class="pb-2">
      <%= user.location %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
    <%= video_tag src="videos/friends.mp4", autoplay: :autoplay, loop: :loop, muted: :muted, class: "vid" %>
    <h1>CampQ</h1>
    <h3>The Experience You've Been Missing Out On</h3>
    <%= link_to "Browse", products_path,  class: "nav-item btn btn-success", id: "browse-btn" %>
</div>
<div class="container">
    <div class="row">
        <section class="content">
            <div class="about">
                <div class="about-section" id="about-camps">
                    <h3>CampQ, a place where you can find and rent out all the essentials for camping</h3>
                    <ul>
                        <li><p><i class="fas fa-plus"></i> Find the camping items you've been looking for</p></li>
                        <li><p><i class="fas fa-plus"></i> Rent the camping gear you've always wanted</p></li>
                        <li><p><i class="fas fa-plus"></i> Rent out your camping items</p></li>
                        <li><p><i class="fas fa-plus"></i> All items rented out at affordable prices</p></li>
                    </ul>
                </div>
                <div class="about-section" id="about-images">
                    <div class="about-images" id="about-img-1">
                        <img src="https://preview.redd.it/i9gtrrh4djv51.jpg?width=960&crop=smart&auto=webp&s=86aedf14f51ba5c5928799c22c4397146bc4511e" alt="">
                    </div>
                </div>
            </div>
        </section>
        <section class="container">

          <h3 id="popular-headerx">Most Popular Camping Items</h3>

            <div class="owl-carousel owl-theme mt-3">
              <% @products.each do |product| %>
              <%= link_to product_path(product) do %>
                <%= render 'popular-card', product: product %>
                <% end %>
              <% end %>
            </div>
        </section>
            </div>
        </section>
        <section class="content">
            <div class="reviews">
                <div class="reviews-story col">
                    <h3>Great stories begin with CampQ</h3>
                    <ul>
                        <li><p>"Good gosh folks! I rented this 2-man tent due to the low price and the high scoring reviews here at CampQ and the reviews are spot on."</p></li>
                        <br>
                        <li><p>"I'm not exactly an expert on boots, this is the most I have ever spent on a pair of hiking boots, and I know they can run 4x the price of these easily. I used to buy nice work boots, and not have enough left over for nice hiking boots, so I either hiked in work boots, or bought $25-30 hiking boots. It was finally time for an upgrade. I couldn't be happier."</p></li>
                        <br>
                        <li><p>"I would recommend this to people. I cant speak to the long term durability as of yet.But sofar I've had no problems and it stood up in heavy down pours/winds with the aid of a tarp. And let me mention the bug netting saved me on a camping trip where i forgot bug spray. The bug mesh worked perfectly. Once i killed all the bugs that got in. ZERO bugs all night and i fell asleep like a baby."</p></li>
                    </ul>
                </div>
                <div class="reviews-image col">
                    <img id="review-img" src="https://external-preview.redd.it/OjnL8CVDIFXnsmnxuJe3pfQex3kk1WduBE0gpCMQqUs.jpg?auto=webp&s=9e145973a3fc86529bec1ffe5d2ea274a2babc18" alt="">
                </div>
            </div>
        </section>
        <section class="content">
            <div class="search">
                <h3 id="search-header">Discover the camping experience you've been missing out on</h3>
                <%#= simple_form_for :search, url: products_path, method: "GET", html: { class: 'form-inline' } do |f| %>
                    <%#= f.input :name, input_html: {value: ""} %>
                    <%#= f.submit "Search", class: "btn btn-primary" %>
                <%# end %>
                <%= link_to "Browse", products_path,  class: "nav-item btn btn-success", id: "browse-btn" %>
        </section>
    </div>
</div>

app/views/pages/profile.html.erb
<div class="container p-16">
  <h1 style="text-align: center" class="m-4 4">Dashboard</h1>

  <h1>My Gear</h1>
  <%= render 'gear_card', bookings: @bookings %>

  <div class="d-flex mt-sm-4">
    <div style="text-align: center; padding: 32px; margin-top: 64px; margin-right: 32px;">
      <img src=" <%= current_user.picture %>" class="avatar-profile" alt="Avatar">
      <h2>Hello <%=current_user.first_name%>!</h2>
      <h4><%=current_user.email%></h4>
      <h4><%=current_user.location%></h4>
    </div>
    <div>
      <%= month_calendar(events: @bookings, attribute: :start_time, end_attribute: :end_time) do |date, bookings| %>
        <%= date %>
        <% bookings.each do |booking| %>
          <div class="booking-profile-calendar">
            <p><%= booking.product.name %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
    <hr>
  <h1 style="text-align: center" class="m-4 4">Bookings</h1>
    <div class="container py-3">
 <div class="container py-3">
    <ul class="nav tabs-underlined" id="myTab" role="tablist">
      <!-- my profile -->
      <li class="nav-item" role="presentation">
        <a class="active tab-underlined" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="true">My profile</a>
      </li>
      <!-- my rentals -->
      <li class="nav-item" role="presentation">
        <a class="tab-underlined" id="rentals-tab" data-toggle="tab" href="#requests" role="tab" aria-controls="my_rentals" aria-selected="false">My rentals</a>
      </li>
      <!-- requests -->
      <li class="nav-item" role="presentation">
        <a class="tab-underlined" id="requests-tab" data-toggle="tab" href="#bookings" role="tab" aria-controls="home" aria-selected="true">Requests</a>
      </li>
      <!-- my listings -->
       <li class="nav-item" role="presentation">
        <a class="tab-underlined" id="listings-tab" data-toggle="tab" href="#lists" role="tab" aria-controls="profile" aria-selected="false">My listings</a>
      </li>
    </ul>

    <div class="tab-content" id="myTabContent">
      <!-- my profile -->
      <div class="tab-pane fade py-3 show active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        <div class="d-flex justify-content-around mt-5">
          <div>
            <%= render 'profile_tab', user: @user %>
          </div>
          <div>
            <%= render 'profile_calendar', bookings: @bookings, rental_bookings: @rental_bookings %>
          </div>
        </div>
      </div>

      <!-- my rentals -->
      <div class="tab-pane fade py-3 pt-3" id="requests" role="tabpanel" aria-labelledby="requests-tab">
        <% if @bookings.present? %>
          <p class="m-3 fs-6">Check the status of your rental requests.</p>
          <%= render 'gear_card', bookings: @bookings %>
        <% else %>
          <p>You have not requested any rentals at this time.</p>
        <% end %>
      </div>

      <!-- requests -->
      <div class="tab-pane fade py-3  pt-3" id="bookings" role="tabpanel" aria-labelledby="rentals-tab">
        <% if @rental_bookings.present? %>
          <p class="m-3 fs-6">Check the status of your rental requests. Accept/reject any pending requests.</p>
          <%= render 'gear_card', bookings: @rental_bookings %>
        <% else %>
          <p>There are no requests for your gear at this time.</p>
        <% end %>

      </div>
      <div class="tab-pane fade py-3" id="requests" role="tabpanel" aria-labelledby="profile-tab">
        <div class="row">
          <% @bookings.each do |booking| %>
            <div class="col-4 mt-4">
              <div class="img-profile">
                <span class="card-category py-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path booking.product.photos[0].key, width: 100 %>);">
                </span>
                <ul id="details">
                  <li><b>Booking status: </b><%= booking.status %></li>
                  <li><b>Price: </b> ￥<%= booking.product.price %></li>
                  <li><b>From: </b><%= booking.start_time.to_date %></li>
                  <li><b>To: </b><%= booking.end_time.to_date %></li>
                </ul>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

      <!-- my listings -->
      <div class="tab-pane fade py-3  pt-5" id="lists" role="tabpanel" aria-labelledby="listings-tab">
        <% if @user.products.present? %>
          <%= render 'listing_card', products: @user.products %>
        <% else %>
          <p class="m-3">No products listed. Click 'List your gear' and create your first listing.</p>
        <% end %>
      </div>
    </div>
 </div>

app/views/products/_form.html.erb
<%= simple_form_for product do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :category, collection: ["Tent", "Camp Kitchen", "Sleeping Bags", "Hammocks"], prompt: 'Select category', label: false %>
  <%= f.input :photos, as: :file, input_html: { multiple: true }, label: "Upload picture(s) of your product" %>
  <%= f.submit "Create a new item", class: 'add-to-cart w-100' %>
<% end %>

app/views/products/_info_window.html.erb
<%= cl_image_tag product.photos[1].key, width: 100 %>
<h4 class="mt-2"><%= product.name %></h4>
<h5>$<%= product.price %></h5>

app/views/products/new.html.erb
<div class="container mt-4 my-4">
  <div class="col-6 m-auto">
    <div class="product-form">
      <h1>Add a new item</h1>
      <div class="mt-3">
          <%= render 'form', product: @product %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="product-page">
  <nav class="flex-nav">
  <div class="product-container">
    <div class="grid menu">
      <div class="column-xs-8 column-md-6">
       <!-- <p id="highlight"> <%= link_to "CampQ", root_path %></p> -->
      </div>
      <div class="column-xs-4 column-md-6">
        <a href="#" class="toggle-nav">Menu <i class="ion-navicon-round"></i></a>
        <ul>
          <li class="nav-item"><a href="/products">Products</a></li>
          <li class="nav-item"><a href="/">About</a></li>
          <li class="nav-item"><a href="/profile">My rentals</a></li>
          <li class="nav-item"><a href="#">Cart (0)</a></li>
        </ul>
      </div>
    </div>
  </div>
  </nav>
  <main>
    <div class="product-container">
      <div class="grid second-nav">
        <div class="column-xs-12">
          <nav>
            <ol class="breadcrumb-list">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item"><a href="#"> <%= @product.category %></a></li>
              <li class="breadcrumb-item active"> <%= @product.name %></li>
            </ol>
          </nav>
        </div>
      </div>
      <div class="grid product d-flex">
        <div class="column-xs-12 column-md-7">
          <div class="product-gallery">
            <div class="product-image">
              <%= cl_image_tag @product.photos[0].key, class: "active" %>
            </div>
            <ul class="image-list">
              <li class="image-item"><%= cl_image_tag @product.photos[0].key, width: 100 %></li>
              <li class="image-item"><%= cl_image_tag @product.photos[1].key, width: 100 %></li>
              <li class="image-item"><%= cl_image_tag @product.photos[2].key, width: 100 %></li>
            </ul>
  
          </div>
        </div>
        <div class="column-xs-12 column-md-5">
          <h1><%= @product.name %></h1>
          <h2>¥ <%= @product.price %></h2>
          <div class="description">
            <p> <%= @product.description %></p>
          </div>
          <%= link_to(new_product_booking_path(@product)) do %>
            <% if @product.user != current_user %>
               <button class="add-to-cart">Reserve this item</button>
            <% end %>
            <% end %>
        </div>
      </div>
      <div class="related-products py-3">
        <div class="column-xs-12">
          <h3>You may also like</h3>
        </div>
        <div class="d-flex justify-content-between p-2">
            <% @random_product.each do |random_product| %>
            <%= link_to(product_path(random_product)) do %>
             <div class="recommended-item column-xs-12 column-md-4 mx-1">
                 <%= cl_image_tag random_product.photos[1].key, style: "height: 320px; width: 480px; object-fit: contain;" %>
                 <h4><%= random_product.name %></h4>
                 <p class="price">¥ <%= random_product.price %></p>
             </div>
           <% end %>
           <% end %>
           </div>
        </div>
      </div>
  </main>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-transparent">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= link_to root_path do %>
        <% image_tag "favicon.ico" %>
      <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to "Browse", products_path,  class: "nav-item" %>
        <div class="dropdown">
            <button id="dropdownMenuButton" class="dropdown-toggle" type="button" data-toggle="dropdown">Locations</button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Tokyo</a>
                <a class="dropdown-item" href="#">Osaka</a>
                <a class="dropdown-item" href="#">Kyoto</a>
            </div>
        </div>
        <ul class="navbar-nav ml-auto mr-auto">
            <li class="nav-item">
                <div class="justify-content-md-center">
                  <%= form_tag products_path, method: :get, class: "form-inline my-2 my-lg-0", style: "width: 17rem;" do %>
                    <%= text_field_tag :query,
                      params[:query],
                      class: "form-control",
                      placeholder: "Ex. Tent"
                    %>
                    <%= submit_tag "Search", class: "btn btn-primary" %>
                  <% end %>
                  <%# <form class="form-inline my-2 my-lg-0" style="width: 50rem;" action="/products">
                      <input class="form-control mr-sm-2" type="search" placeholder="Ex. Tent" style="font-style: italic; width: 29rem;" aria-label="Search" name="query">
                      <button id="search" class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
                  </form> %>
                </div>
            </li>
        </ul>
        <% if user_signed_in? %>
        <ul class="d-inline-flex" style="gap: 2rem;">
            <li class="nav-item">
              <%= link_to "List your gear", new_product_path, class: "btn btn-primary" %>
            </li>
            <li class="nav-item dropdown">
              <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "My profile", "/profile", class: "dropdown-item" %>
                <%= link_to "My own gear", "#", class: "dropdown-item" %>
                <%= link_to "My rental gear", "#", class: "dropdown-item" %>
              </div>
            </li>
        </ul>
        <% else %>
        <ul class="nav-btn-item d-inline-flex">
            <li class="nav-item">
              <%= link_to "List your gear", new_product_path, class: "btn btn-primary" %>
            </li>
            <li class="nav-item">
              <div class="btn-nav">
                  <%= link_to "Login", new_user_session_path, class: "btn btn-success"%>
              </div>
            </li>
            <li class="nav-item">
              <div class="btn-nav">
                  <%= link_to "Sign Up", new_user_registration_path , class: "btn btn-success"%>
              </div>
            </li>
        </ul>
        <% end %>
    </div>
</nav>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>